### PR TITLE
Fix VALID ID not set

### PR DESCRIPTION
**Pull request by ymebrugts**
On startup during PLL1 load from device trees a valid ID is set. This valid id is checked upon entering sleep (CStop) inside "stm32mp1_clk_lp_save_opp_pll1_settings".

When starting from CStop (0x814 reset reason) the Valid ID is not set because the context is acquired from RAM. If context is valid it should also set the ID to valid so that the system doesn't crash if CStop is used again.

Best regards,
Yme Brugts

### CODE REVIEW

**Comment by Yann-lms** [comment]
Hi @ymebrugts,

Thanks for your patch, and sorry for the late reply.

We do not directly merge pull requests here.
Instead, we've raised an internal ticket, which is being checked by our clock and power expert.
If your patch is OK (or an updated one if necessary), it will be merged internally, and the new branch will be pushed to github.

Till the correction is pushed, I'll let this P-R opened.

Best regards,
Yann

**Comment by Yann-lms** [comment]
Hi @ymebrugts,

It seems there is a wrong behavior with the board you are testing.
Is it an STMicroelectronics board?
Do you have the TF-A traces (boot and return from Standby)?

When returning from Standby, the BIT(2) (RCC_MP_RSTSCLRR_PADRSTF) shouldn't be set in the RCC_MP_RSTSCLRR register, used to determine reset reason.
As this bit is set, a part of code in plat_get_bl_image_load_info() is not executed. And the clock config is then not restored in sp_min_plat_get_bl33_ep_info().

As the Pad reset bit is set, the return from Standby procedure shouldn't be done. The wakeup_standby variable should then not be true. We should complete the test on boot_action with the test of this Pad reset bit.

But again, this behavior is not expected, so any information on how to reproduce it is welcome.

Thanks,
Yann

**Comment by ymebrugts** [comment]
Hi Yann, 

Interesting. It's a custom in-house designed board with custom device tree files. I can share those files if you give me a way to share those privately. They should be fine as is. 

Note that my issue only happens in a specific scenario. The device goes to sleep and then while in sleep it gets reset and turned on like normal (so not returning from standby). So the below "ON" function is called while in sleep which calls reset() and then wake_up(). The device turns on normally from standby (so **not** returning from standby) by calling the on() function but putting the device in standby at this point and returning it from standby by just waking it up with wake_up() will crash Linux originating from the TF-A code. 

```
    def on(self):
        self.reset()
        sleep_ms(100)
        self.wake_up()
        if self.verbose:
            print("MP1_ON")

    def reset(self):
        # reset low active
        self.mp1_reset.value(0)
        sleep_ms(100)
        self.mp1_reset.value(1)
        if self.verbose:
            print("MP1_RESET")

    def wake_up(self):
        self.mp1_wakeup.value(1)
        sleep_ms(100)
        self.mp1_wakeup.value(0)
        if self.verbose:
            print("MP1_WAKEUP")
```

I do have earlyprintk traces if that's what you're looking for but it'll take a little bit of effort. I do have an image of the difference between startup by waking up normally from standby and resetting while in standby. Let me know if the image below is good enough:
Left = normal startup from off
Right = startup from standby by calling on()
Screenshot from 2021-07-19 17-08-37
 


We are using v2.2-stm32mp with the latest commit shown below:
image


Best regards,
Yme

**Comment by Yann-lms** [comment]
Hi Yme,

That confirms what I thought, we should properly check RCC_MP_RSTSCLRR_PADRSTF when returning from Standby.
Here is the patch I plan to push:

diff --git a/plat/st/stm32mp1/bl2_plat_setup.c b/plat/st/stm32mp1/bl2_plat_setup.c
index 746348d9e..1f3b9c92b 100644
--- a/plat/st/stm32mp1/bl2_plat_setup.c
+++ b/plat/st/stm32mp1/bl2_plat_setup.c
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2015-2020, ARM Limited and Contributors. All rights reserved.
+ * Copyright (c) 2015-2021, ARM Limited and Contributors. All rights reserved.
  *
  * SPDX-License-Identifier: BSD-3-Clause
  */
@@ -338,6 +338,7 @@ void bl2_el3_plat_arch_setup(void)
                tamp_bkpr(BOOT_API_CORE1_MAGIC_NUMBER_TAMP_BCK_REG_IDX);
        uint32_t bkpr_core1_addr =
                tamp_bkpr(BOOT_API_CORE1_BRANCH_ADDRESS_TAMP_BCK_REG_IDX);
+       uint32_t rstsr;
 
        mmap_add_region(BL_CODE_BASE, BL_CODE_BASE,
                        BL_CODE_END - BL_CODE_BASE,
@@ -421,10 +422,12 @@ void bl2_el3_plat_arch_setup(void)
                      TAMP_BKP_SEC_NUMBER << TAMP_BKP_SEC_WDPROT_SHIFT |
                      TAMP_BKP_SEC_NUMBER << TAMP_BKP_SEC_RWDPROT_SHIFT);
 
-       if ((boot_context->boot_action !=
-            BOOT_API_CTX_BOOT_ACTION_WAKEUP_CSTANDBY) &&
-           (boot_context->boot_action !=
-            BOOT_API_CTX_BOOT_ACTION_WAKEUP_STANDBY)) {
+       rstsr = mmio_read_32(stm32mp_rcc_base() + RCC_MP_RSTSCLRR);
+       if (((boot_context->boot_action !=
+             BOOT_API_CTX_BOOT_ACTION_WAKEUP_CSTANDBY) &&
+            (boot_context->boot_action !=
+             BOOT_API_CTX_BOOT_ACTION_WAKEUP_STANDBY)) ||
+           ((rstsr & RCC_MP_RSTSCLRR_PADRSTF) != 0U)) {
                mmio_write_32(bkpr_core1_addr, 0);
                mmio_write_32(bkpr_core1_magic, 0);
        }

Can you check if it solves your issue?

Thanks,
Yann

**Comment by Yann-lms** [comment]
That's not really readable, sorry

`
diff --git a/plat/st/stm32mp1/bl2_plat_setup.c b/plat/st/stm32mp1/bl2_plat_setup.c
index 746348d9e..1f3b9c92b 100644
--- a/plat/st/stm32mp1/bl2_plat_setup.c
+++ b/plat/st/stm32mp1/bl2_plat_setup.c
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2015-2020, ARM Limited and Contributors. All rights reserved.
+ * Copyright (c) 2015-2021, ARM Limited and Contributors. All rights reserved.
  *
  * SPDX-License-Identifier: BSD-3-Clause
  */
@@ -338,6 +338,7 @@ void bl2_el3_plat_arch_setup(void)
                tamp_bkpr(BOOT_API_CORE1_MAGIC_NUMBER_TAMP_BCK_REG_IDX);
        uint32_t bkpr_core1_addr =
                tamp_bkpr(BOOT_API_CORE1_BRANCH_ADDRESS_TAMP_BCK_REG_IDX);
+       uint32_t rstsr;
 
        mmap_add_region(BL_CODE_BASE, BL_CODE_BASE,
                        BL_CODE_END - BL_CODE_BASE,
@@ -421,10 +422,12 @@ void bl2_el3_plat_arch_setup(void)
                      TAMP_BKP_SEC_NUMBER << TAMP_BKP_SEC_WDPROT_SHIFT |
                      TAMP_BKP_SEC_NUMBER << TAMP_BKP_SEC_RWDPROT_SHIFT);
 
-       if ((boot_context->boot_action !=
-            BOOT_API_CTX_BOOT_ACTION_WAKEUP_CSTANDBY) &&
-           (boot_context->boot_action !=
-            BOOT_API_CTX_BOOT_ACTION_WAKEUP_STANDBY)) {
+       rstsr = mmio_read_32(stm32mp_rcc_base() + RCC_MP_RSTSCLRR);
+       if (((boot_context->boot_action !=
+             BOOT_API_CTX_BOOT_ACTION_WAKEUP_CSTANDBY) &&
+            (boot_context->boot_action !=
+             BOOT_API_CTX_BOOT_ACTION_WAKEUP_STANDBY)) ||
+           ((rstsr & RCC_MP_RSTSCLRR_PADRSTF) != 0U)) {
                mmio_write_32(bkpr_core1_addr, 0);
                mmio_write_32(bkpr_core1_magic, 0);
        }
`

**Comment by Yann-lms** [comment]
Well, not better sorry.
Here is the patch, in my own github:
https://github.com/Yann-lms/arm-trusted-firmware/commit/d4ad28b07371c0ad6c4a4596399b39c772a72e87

Once it is verified, it will be published here.

**Comment by Yann-lms** [comment]
The patch to correct the issue was pushed there:
https://github.com/STMicroelectronics/arm-trusted-firmware/commit/458963b0707733711ff842e854719d9d2cf4833d

We can close this PR.

Regards,
Yann

**Comment by ymebrugts** [comment]
Thanks! Sorry I did not have the time to test it. It was still in the pipeline though. Will switch to the official patch when I get the time to do so.

**Pull request closed without merging**
